name: Gestor de Clientes Sky

on:
  workflow_dispatch:
    inputs:
      accion:
        description: 'Acción a realizar'
        required: true
        default: 'listar'
        type: choice
        options:
          - listar
          - ver
          - crear
          - agregar_servicio
      nombre:
        description: 'Nombre del cliente'
        required: false
      direccion:
        description: 'Dirección del cliente'
        required: false
      telefono:
        description: 'Teléfono del cliente'
        required: false
      servicio:
        description: 'Servicio para el cliente'
        required: false

jobs:
  gestionar-clientes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Ejecutar gestor de clientes
        run: |
          python gestor_clientes_sky.py ${{ github.event.inputs.accion }} \
            --nombre "${{ github.event.inputs.nombre }}" \
            --direccion "${{ github.event.inputs.direccion }}" \
            --telefono "${{ github.event.inputs.telefono }}" \
            --servicio "${{ github.event.inputs.servicio }}"
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add clientes/
          git commit -m "Actualización de clientes" || echo "No changes to commit"
          git push
