name: Gestor de Clientes Sky

on:
  workflow_dispatch:
    inputs:
      accion:
        description: 'Acción a realizar'
        required: true
        default: 'listar'
        type: choice
        options:
          - listar
          - ver
          - crear
          - agregar_servicio
      nombre:
        description: 'Nombre del cliente'
        required: false

jobs:
  ejecutar-gestor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Verificar entorno
        run: |
          python --version
          ls -la
